owner: hariidfidina20-sudo
repo: SERVER-MONITORING

sites:
  - name: PROXMOX UTAMA
    url: $MY_PROXMOX_URL
    __dangerous__insecure: true
    expectedStatusCodes: [200, 30x, 401]
  - name: ZAHIR
    url: $MY_ZAHIR_URL
    __dangerous__insecure: true
    expectedStatusCodes: [200, 30x, 401]
  - name: LOWCODER
    url: $MY_LOWCODER_APP1_APP2
    expectedStatusCodes: [200]
  - name: HOMEBOOK
    url: $MY_INVENTARIS_INSANTAQWA
    expectedStatusCodes: [200]
  - name: TB40
    url: $MY_TB40_URL
    expectedStatusCodes: [200]
  - name: RAPOR SD
    url: $MY_RAPOR_SD_INSAN_TAQWA
    expectedStatusCodes: [200]
    
status-website:
  baseUrl: /SERVER-MONITORING
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitoring Server
  introTitle: "Sistem Monitoring Server"
  introMessage: "Memantau layanan Proxmox, Zahir, dan Insan Taqwa secara otomatis."
  navbar:
    - title: Status
      href: /SERVER-MONITORING/
    - title: GitHub
      href: https://github.com/hariidfidina20-sudo/SERVER-MONITORING

workflowSchedule:
  graphs: "0 0 * * *"
  staticSite: "0 1 * * *"
  summary: "0 2 * * *"
  uptime: "*/5 * * * *"
