owner: hariidfidina20-sudo
repo: SERVER-MONITORING

sites:
  - name: Proxmox Utama
    url: $MY_PROXMOX_URL
    __dangerous__insecure: true
    expectedStatusCodes:
      - 200
      - 30x
      - 401
  - name: Zahir
    url: $MY_ZAHIR_URL
    __dangerous__insecure: true
    expectedStatusCodes:
      - 200
      - 30x
      - 401
    - name: Zahir
    url: $MY_LOWCODER_APP1_APP2
    __dangerous__insecure: true
    expectedStatusCodes:
      - 200
      - 30x
      - 401

status-website:
  # CNAME harus dihapus jika tidak pakai domain sendiri agar tidak bentrok
  baseUrl: /SERVER-MONITORING
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitoring Server
  introTitle: "Sistem Monitoring Server"
  introMessage: "Halaman ini memantau status server Proxmox dan Zahir secara real-time."
  navbar:
    - title: Status
      href: /SERVER-MONITORING/
    - title: GitHub
      href: https://github.com/hariidfidina20-sudo/SERVER-MONITORING
